//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebBAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public int accountNo { get; set; }
        public int balance { get; set; }
        public int pin { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string icon64 { get; set; }
    }
}
